version: '3'

services:
  web:
    # container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src'
    env_file: 
      - .env
    ports:
      - 5000:5000
      - 8010:8000
    depends_on:
      - db

  db:
    image: postgres:12-alpine 
    # container_name: db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
