"""empty message

Revision ID: c8e70d1daa16
Revises: 
Create Date: 2020-06-17 23:56:14.780742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8e70d1daa16"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "friendships",
        sa.Column("friend_a", sa.Integer(), nullable=False),
        sa.Column("friend_b", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["friend_a"], ["users.id"],),
        sa.ForeignKeyConstraint(["friend_b"], ["users.id"],),
        sa.PrimaryKeyConstraint("friend_a", "friend_b"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friendships")
    op.drop_table("users")
    # ### end Alembic commands ###
