"""empty message

Revision ID: eb820f85ccf0
Revises: c8e70d1daa16
Create Date: 2020-06-18 00:11:29.125979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb820f85ccf0"
down_revision = "c8e70d1daa16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "friendships",
        sa.Column("friend_a", sa.Integer(), nullable=False),
        sa.Column("friend_b", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["friend_a"], ["users.id"],),
        sa.ForeignKeyConstraint(["friend_b"], ["users.id"],),
        sa.PrimaryKeyConstraint("friend_a", "friend_b"),
    )
    op.drop_table("user")
    op.drop_table("friendship")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendship",
        sa.Column("friend_a", sa.INTEGER(), nullable=False),
        sa.Column("friend_b", sa.INTEGER(), nullable=False),
        sa.Column("status", sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(["friend_a"], ["user.id"],),
        sa.ForeignKeyConstraint(["friend_b"], ["user.id"],),
        sa.PrimaryKeyConstraint("friend_a", "friend_b"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.drop_table("friendships")
    op.drop_table("users")
    # ### end Alembic commands ###
